spring:
  datasource:
    url: jdbc:h2:mem:cinema-booking-system
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: '/console'

flyway:
  baselineOnMigrate: true

ticket:
  max-paid-age: 15